import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Venco from './Venco.jpg'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Venco Mladiot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.title}>
          Izvini shto dojde.
        </p>
        <Image src={Venco} alt="Slika od venco" width={350} height={350} />
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
